remote_theme: mmistakes/minimal-mistakes@4.24.0
plugins:
  - jekyll-include-cache
  - jekyll-archives
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme
